### ISSUE TITLE
Add Docker to a DigitalOcean droplet ☁️

### ISSUE THREAD

**Issue by BaggioGiacomo** [inkOfPixel/inkofpixel.com#193]
# How to install Docker on a DigitalOcean droplet 🚀
1. Create a DigitalOcean account.
2. Create a droplet using Docker integration on **Marketplace** tab. In your dashboard you will see a menu in the left side. If you press on **Droplets** you will find your brand new droplet.
3. Press on the Docker logo that said Get Started and get the ssh ip address. It should looks like this: ```ssh root@xxx.xxx.xxx.xxx```
4. Open your favourite terminal, paste your address and you will be inside your droplet!
5. Typing ``` sudo systemctl status docker ``` you can see that Docker is installed and active.
6. Now you can use Docker commands. To view all of them just type ```docker```.
7. To check whether you can access and download images from Docker Hub, type: 
```docker run hello-world``` 
8. You can search for images available on Docker hub by typing ```Docker search [imageName]```
9. Create a ```Docker-compose.yml``` file that will contain all your services. Here's an example: 
```
version: '3.6'
services:
  strapi:
    image: strapi/strapi
    restart: always
    volumes:
    - ./app:/srv/app
    ports:
    - '1337:1337'
  caddy:
    image: caddy:2-alpine
    depends_on:
    - "strapi"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
```
10. Create a ```Caddyfile``` (if you don't put it in the same directory of the ```Docker-compose.yml``` file, remember to change the path under ```volumes```.  Here's the the ```Caddyfile```:
```
<your domain name> {
  reverse_proxy strapi:1337
}
```
⚠️ Don't use tabulation when creating the ```Docker-compose.yml``` file, use spaces instead ⚠️ 
ℹ️ Caddy is a web server that offers us an automatic https management. It gets SSL certifcates automatically by LetsEncrypt ℹ️ 
11. It's time to create our container! You just have to run ```docker-compose up``` command. Adding -d flag will run it in background.
12. Strapi will start building, it will take about 2 minutes.
13. After the build phase you will be able to access Strapi interface from your pc by ```https://<droplet address or domain name>/admin``` . 
14. This page will be encrypted by Caddy 🔒
